-- No se crean productos ficticios automáticamente.
-- La muestra usa las diez joyas fotografiadas definidas en lib/sample-catalog.ts.
-- Aplica migrations/20261002_sample_catalog.sql y carga desde Admin > Ajustes.
-- Guía y limitaciones: docs/ADMIN_GUIDE.md y docs/ENGINEERING_REVIEW.md.
